version: "3"
services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 3333:3333
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
